# Generated by Django 5.1.4 on 2026-01-29 21:43

import django.db.models.deletion
from django.db import migrations, models


TIPOS_INICIALES = [
    ("BAJA_CUANTIA", "Baja cuantía", "baja-cuantia", 1),
    ("COMPRA_DIRECTA", "Compra directa", "compra-directa", 2),
    ("COTIZACION", "Cotización", "cotizacion", 3),
    ("CONTRATO_ABIERTO", "Contrato abierto", "contrato-abierto", 4),
    ("LICITACION", "Licitación", "licitacion", 5),
]


def seed_tipos_proceso(apps, schema_editor):
    TipoProcesoCompra = apps.get_model("scompras_app", "TipoProcesoCompra")
    ProcesoCompraPaso = apps.get_model("scompras_app", "ProcesoCompraPaso")
    SolicitudCompra = apps.get_model("scompras_app", "SolicitudCompra")

    codigo_map = {}
    for legacy_codigo, nombre, codigo, orden in TIPOS_INICIALES:
        tipo, _ = TipoProcesoCompra.objects.get_or_create(
            codigo=codigo,
            defaults={
                "nombre": nombre,
                "activo": True,
                "orden": orden,
            },
        )
        if tipo.nombre != nombre or tipo.orden != orden or not tipo.activo:
            tipo.nombre = nombre
            tipo.orden = orden
            tipo.activo = True
            tipo.save(update_fields=["nombre", "orden", "activo"])
        codigo_map[legacy_codigo] = tipo.id

    for legacy_codigo, _, _, _ in TIPOS_INICIALES:
        tipo_id = codigo_map.get(legacy_codigo)
        if tipo_id is None:
            continue
        ProcesoCompraPaso.objects.filter(tipo_proceso=legacy_codigo).update(
            tipo_proceso_fk_id=tipo_id
        )
        SolicitudCompra.objects.filter(tipo_proceso=legacy_codigo).update(
            tipo_proceso_fk_id=tipo_id
        )


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ("scompras_app", "0026_seed_proceso_pasos"),
    ]

    operations = [
        migrations.CreateModel(
            name="TipoProcesoCompra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=80, unique=True)),
                ("codigo", models.SlugField(max_length=40, unique=True)),
                ("activo", models.BooleanField(default=True)),
                ("orden", models.PositiveIntegerField(default=0)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["orden", "nombre"],
            },
        ),
        migrations.AddField(
            model_name="procesocomprapaso",
            name="tipo_proceso_fk",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pasos",
                to="scompras_app.tipoprocesocompra",
            ),
        ),
        migrations.AddField(
            model_name="solicitudcompra",
            name="tipo_proceso_fk",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="scompras_app.tipoprocesocompra",
            ),
        ),
        migrations.RunPython(seed_tipos_proceso, noop_reverse),
        migrations.RemoveField(model_name="procesocomprapaso", name="tipo_proceso"),
        migrations.RemoveField(model_name="solicitudcompra", name="tipo_proceso"),
        migrations.RenameField(
            model_name="procesocomprapaso",
            old_name="tipo_proceso_fk",
            new_name="tipo_proceso",
        ),
        migrations.RenameField(
            model_name="solicitudcompra",
            old_name="tipo_proceso_fk",
            new_name="tipo_proceso",
        ),
        migrations.AlterField(
            model_name="procesocomprapaso",
            name="tipo_proceso",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pasos",
                to="scompras_app.tipoprocesocompra",
            ),
        ),
    ]
